pipeline {
    agent any
    environment{
        RegistryURL = "https://registry.hub.docker.com/"
        RepoName = "sarangp007/jenkins_docker"
        dh_creds = 'dockerhub_creds'
    }
    stages{
        stage('Builing image') {
            environment{
                registry_endpoint = "${env.RegistryURL}" + "${env.RepoName}"
                tag = "${env.RepoName}" + "$GIT_COMMIT"
            }
            steps{
                script{
                     docker.withRegistry(registry_endpoint, dh_creds) {

                     def Image = docker.build(tag)

                     /* Push the container to the custom Registry */
                     Image.push()

                 }
            }

        }
    }
    
    }
  
}
//https://hub.docker.com/r/sarangp007/jenkins_docker